/*
 * compiler-main.cpp
 *
 * Main file used to make the MITScript compiler (takes in MITScript
 * source code, generates a root bytecode function, and pretty-prints the
 * generated bytecode)
 */
#include "../parser/ms/parser.h"
#include "../parser/ms/lexer.h"
#include "../parser/bc/printer.h"
#include "bc-compiler.h"
#include <iostream>

using namespace std;

int main(int argc, char** argv)
{
    void* scanner;
    yylex_init(&scanner);

    if (argc < 2) {
        cout << "Expecting file name as argument" << endl;
        return 1;
    }
    FILE* infile = fopen(argv[1], "r");
    if (infile == NULL) {
        cout << "Cannot open file " << argv[1] << endl;
        return 1;
    }
    yyset_in(infile, scanner);

    Block* output;
    int rvalue = yyparse(scanner, output);
    if (rvalue == 1) {
        cout << "Parsing MITScript failed" << endl;
        return 1;
    }

    BytecodeCompiler* bc = new BytecodeCompiler();

    try {
        Function* rootFunc = bc->evaluate(*output);
        PrettyPrinter printer;
        printer.print(*rootFunc, std::cout);
    } catch (InterpreterException& exception) {
        cout << exception.toString() << endl;
        return 1;
    }

    return 0;
}
